services:

  glue:
      build: 
        context: .
      container_name: glue_aggregation_job
      volumes:
        - ./src/glue_job/glue_script:/home/glue/scripts
      env_file:
        - ./.env
      working_dir: /home/glue/scripts
      stdin_open: true

  lambda:
    image: python:3.11-slim
    volumes:
        - ./src/lambda:/home/app/
    command: python /home/app/lambda_function.py
